name: redis_dart_link
version: 0.0.1
description: Redis / Resp agreement database  client.
homepage: https://github.com/toolsetlink/redis_dart_link
repository: https://github.com/toolsetlink/redis_dart_link
issue_tracker: https://github.com/toolsetlink/redis_dart_link/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.6.5