name: redis_dart_link
version: 0.0.6
description: A Redis SDK in Dart that encapsulates Redis commands to enhance development efficiency for data storage and management.
homepage: https://github.com/toolsetlink/redis_dart_link
repository: https://github.com/toolsetlink/redis_dart_link
issue_tracker: https://txc.qq.com/products/645521

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.6.5
